### ISSUE TITLE
Interne links in rapporten werken lay-out matig niet goed

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#1]
In rapporten werken interne links (\<A href="##herleeftijd"> naar <A id="herleeftijd"></A>, vb rapport diversiteit) niet meer goed. De pagina landt wel zo ongeveer op de juist plaats, maar de gelinkte titel is vaak niet eens in beeld. Dit werkte vroeger wel.

**Comment by EdwardABF** [comment]
Ik heb dit zojuist getest en het werkt (nu) goed. Wellicht is dit in de tussentijd al opgelost. Is het mogelijk om dit opnieuw te testen?

**Comment by joostschouppe** [comment]
Juist, deze had al afgesloten mogen worden.
