### ISSUE TITLE
metadatafiche pendel woon-werk

### ISSUE THREAD

**Issue by EDebever** [provinciesincijfers/bugsinjive#101]
Hallo,

De linkjes naar metadatafiches van pendel in/uit woon-werk werken niet op PinC.
![image](https://user-images.githubusercontent.com/35772127/176376768-e7d69b2c-004c-4c13-b714-09bc969f270d.png)

Mvg,
Ellen

**Comment by joostschouppe** [comment]
Bedankt voor de melding. Het is gefixed in admin, zie https://provincies.incijfers.be/admin/info/bron_steunpunt_werk.html
