### ISSUE TITLE
Nieuwe benamingen statistische sectoren

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/bugsinjive#102]
Niet echt een bug maar een vraag: zonet is de update van de statistische sectoren 2022 gepubliceerd.  Mechelen heeft van de gelegenheid gebruik gemaakt om een aantal namen van sectoren aan te passen.  Hoe krijgen we die nieuwe namen in Swing?  Is dat iets dat ABF moet doen, PinC of wijzelf?

**Comment by joostschouppe** [comment]
De namen beheer je (gedeeltelijk zelf). Via Data>Geolevels> en dan Areas van de geolevel met je statistische sectoren kan je ze één voor één aanpassen. Heb je een hele lijst die je wil aanpassen, dan moet je het aan ABF vragen - enkel zij kunnen metadata van geolevels importeren.
De benamingen aan kant PinC hebben geen impact op jullie versie. Mochten er echt inhoudelijke wijzigingen aan de statsec zijn (nieuwe gebiedscode, sterk aangepaste geometrie), dan moeten we natuurlijk wel afstemmen. Maar wel goed om weten: wij houden voorlopig versie 2020 van de statsec vast, maar we kunnen wel eens de namen updaten met versie 2022!

**Comment by dimitrivanbaelen** [comment]
Hallo Joost,

Bedankt voor de feedback. Er zijn geen wijzigingen in codes of geometrie, we hebben wel 42 van de 97 namen aangepast.  In veel gevallen gaat het om het verbeteren van de schrijfwijze (voluit schrijven afkortingen, consistentie in spaties, overal BRUG ipv BURG), maar ook een paar echt inhoudelijke wijzigingen.  Ik heb ondertussen de aanpassingen in onze Swing gedaan, maar het zou dus ook fijn zijn als jullie een update van de namen zouden kunnen doen, anders zitten we met een discrepantie tussen PinC en MinC.
