### ISSUE TITLE
labeling is verkeerd

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/bugsinjive#103]
de grafiek toont ratio kandidaat huurders voor Vlaanderen en West-Vlaanderen. de lijntjes liggen redelijk dicht bij elkaar. voor de laatste jaar 2 staat de waarde voor WVL bij VL. Dit is verwarrend. 

https://provincies.incijfers.be/databank?workspace_guid=a92bef52-60b8-4732-8dda-01e2c1bb4928

**Comment by joostschouppe** [comment]
Bedankt, ik geef hem door.

**Comment by joostschouppe** [comment]
Dit is blijkbaar een bekend probleem en staat reeds op de lijst van te fixen dingen.
Opvolging via ABF ticket 118359.

**Comment by Emilien-Dupont** [comment]
Dit lijkt opgelost te zijn
