### ISSUE TITLE
Cachen van rapporten na live zetten van jive

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#11]
Na live zetten van Jive, mogelijkheid om rapporten-cache op te laten bouwen zonder dat je dat manueel moet doen. Eventueel enkel op één of enkele gebiedsniveaus

 ** - Gemeld bij ontwikkelaars.

**Comment by joostschouppe** [comment]
Dit is ook voor Provincies in Cijfers heel belangrijk. Met name voor het gebruik van kubussen moet de eerste gebruiker anders lang wachten.

**Comment by EdwardABF** [comment]
Oplossing afgestemd via e-mail.
