### ISSUE TITLE
Naam van de presentatie aanpassen (door eindgebruiker)

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#13]
Sommige klanten willen graag in een presentatie de naam van de onderwerpen aanpassen (om bijvoorbeeld heel lange onderwerpnamen korter te benoemen)
(Doorgegeven door ABF)

**Comment by EdwardABF** [comment]
Deze wens is opgenomen in de lijst met verbeteringen (backlog) maar staat nog niet gepland om te worden ingebouwd. Bij de volgende planning zal deze opnieuw worden beoordeeld.
