### ISSUE TITLE
Link bij presentatie in rapport zou cijfers in nieuw werkbladje naast rapport moeten tonen

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#14]
Zo kan de gebruiker interactief verder werken met de data en de overstap van het gebruik van rapporten naar gebruik van de databank zelf minder beangstigend te maken.
  - Aantallen ipv getransformeerde aantallen weergeven (minder problematisch indien dynamisch zoals hierboven uitgelegd)

*** - 20/12/2016 - NIET BEHANDELD

**Comment by joostschouppe** [comment]
Vind ik een interessant idee. Lijkt mij heel goed als je een rapport open hebt in de gewone user interface. Maar wat moet er gebeuren als je het rapport op een andere manier hebt geopend?

**Comment by EdwardABF** [comment]
Gaat het hier om de iconen waarmee de gegevens in een tabel of Excel worden weergegeven? De tabel wordt nu in een nieuw tabblad geopend. Is het de bedoeling dat deze in Viewer wordt geopend, al dan niet op een nieuw tabblad (binnen Viewer)? Excel-bestanden kunnen niet in Viewer of de browser worden geopend,

**Comment by joostschouppe** [comment]
het gedrag dat Stefanie omschrijft is vergelijkbaar met dat van de zinsnede "Je kan zelf meer leeftijdscategorieën opvragen via de databank Provincies in Cijfers." in [ons rapport over demografie](https://provincies.incijfers.be/?report=steekkaart_demografie). In dit geval krijg je dan

> https://provincies.incijfers.be/jive?cat_open=Bevolking/Bevolkingsprognose&var=v1121_a_t&view=map&period=2017,2027&keepworkspace=true

Dus naar analogie van dit voorbeeld blijf je verder werken op dezelfde workspace en voeg je er een presentatie aan toe die weergeeft wat je op dit moment krijgt door op het knopje voor tabel te klikken.  Ik begreep van Arnold dat deze functie eigenlijk bestaat omwille van de toegankelijkheid. Wij zouden die eerder hergebruiken om mensen toe te leiden naar Jive vanuit rapporten (die op hun beurt vanuit Dashboard worden geopend)

**Comment by joostschouppe** [comment]
Dit leeft ook bij de werkgroep Landbouw

**Comment by EdwardABF** [comment]
Ik begreep van de ontwikkelaars dat dit in de nieuwe release beschikbaar zal zijn. Je krijgt dan dus een extra icoon onder een presentatie die dezelfde presentatie opent in Viewer.

**Comment by joostschouppe** [comment]
Effectief mogelijk nu:
- via user interface: Show Viewer link in reports 
- code: `<ShowViewerLink>True</ShowViewerLink>`

Opgelet:
In PinC ingesteld als Report default (via https://provincies.incijfers.be/admin/studio/AdminProps?sheet=report&class=)
MAAR dan wordt dit ook getoond voor grafieken waar je geen table of excel link wou laten zien. Als de dus dit tegenkomt in je layout-code:
      `<ShowTableLink>False</ShowTableLink>`
      `<ShowExcelLink>False</ShowExcelLink>`
Dan moet dit aangevuld worden met:
      `<ShowViewerLink>False</ShowViewerLink>`
