### ISSUE TITLE
Rapport import is gevaarlijk

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#16]
Stel, je maakt een externe backup van een rapport door van de functie "Rapporten exporteren" gebruik te maken. Je ontwikkelt verder aan je rapport in Jive. Op een later tijdstip neem je je oude rapport vast (bijvoorbeeld om dat daar iets werkte dat nu niet meer werkte), en importeert het opnieuw in Jive. Er wordt dan standaard geen rij toegevoegd, maar het bestaande rapport met dezelfde code wordt overschreven. Op die manier verlies je dus al het werk dat je binnen Studio deed.

Dit is soms wél wenselijk gedrag. En je kan dit vermijden door in je sw5r bestand de code van het rapport te veranderen. Maar wellicht is het wenselijk om de gebruiker minstens een waarschuwing te geven als je op het punt staat dit te doen.

**Comment by EdwardABF** [comment]
Dat lijkt mij inderdaad logisch dat er een melding verschijnt voordat het rapport overschreven. Dit is als verbetering aangemeld als issue 59981.

**Comment by EdwardABF** [comment]
Vanaf versie 5.2.0. verschijnt er een melding als een rapport overschreven gaat worden. Op dat moment kan de actie nog worden geannuleerd. Deze melding verschijnt bij het importeren van presentaties.

**Comment by EdwardABF** [comment]
Het betreft overigens een algemene melding die altijd verschijnt bij het importeren van rapporten, ook als je geen bestaande rapporten gaat overschrijven. Dat wekt waarschijnlijk allen maar vragen op. Dit moet nog worden aangescherpt, maar dat zal iets meer inspanning kosten.

**Comment by joostschouppe** [comment]
Opgelost
