### ISSUE TITLE
Aanpassingen in rapporten gaan soms verloren

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#17]
We hebben er nog geen patroon in gevonden, maar soms worden aanpassingen niet bewaard. Een manier om zeker te zijn dat dit gelukt is, zou zijn als de knop "Opslaan" rood wordt van zodra er iets gewijzigd is. Als je op de rode knop klikt, en het opslaan is gelukt, laat dan de knop terug grijs of groen worden.

EDIT: prioiriteit omdat dit werken in rapporten veel lastiger dan nodig maakt

**Comment by EdwardABF** [comment]
Rapporten worden elke minuut automatisch opgeslagen. Als tijdens het automatisch opslaan het rapport ook handmatig werd opgeslagen, dan ontstond er een conflict en werden de wijzigingen niet opgeslagen. Dit is nu verholpen.

**Comment by EdwardABF** [comment]
Aan de weergave van de buttons is vooralsnog niets gewijzigd.
