### ISSUE TITLE
tabel achter grafiek in rapport

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#19]
Bij deze tabellen wordt geen eenheid getoond.
Het is zeer onduidelijk voor een gebruiker of het hier om aantallen, percentages, ... gaat.
Dit zou vermeld moeten worden bij de titel van de tabel of bij de onderwerpnaam

**Comment by EdwardABF** [comment]
De eenheid wordt standaard onderaan de tabel in de legenda getoond. In jullie versie is deze optie uitgezet in de algemene opmaakinstellingen van de rapporten. Om dit weer in te schakelen, kies in het menu 'Weergave' voor 'Opmaakinstellingen'. Er opent een nieuw scherm met de opmaakinstellingen. Selecteer nu in de dropdown linksboven in het scherm bij 'Sjabloon' voor 'Rapport'. Vink vervolgens bij 'Legenda' de optie 'Toon eenheid in legenda' aan (zie onderstaande afbeelding).

![image](https://user-images.githubusercontent.com/31502648/29917574-a94929c0-8e42-11e7-8300-3bc7f4ee58ab.png)

**Comment by joostschouppe** [comment]
Bedankt! Weer iets bijgeleerd.
