### ISSUE TITLE
korte naam van gebiedsniveau gebruiken in een grafiek in een rapport

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/bugsinjive#20]
Kan ik in onderstaande grafiek IN EEN RAPPORT
ervoor zorgen dat de NAAM KORT van een gebiedsniveau verschijnt (ipv de NAAM)

![afbeelding](https://user-images.githubusercontent.com/31841732/30262759-71eb52da-96d2-11e7-9a55-72855d6e4894.png)

tabel - gebiedsniveaus
![afbeelding](https://user-images.githubusercontent.com/31841732/30262817-bad3417e-96d2-11e7-9ce6-4796052d6e7b.png)

**Comment by StefanJacques** [comment]
Sander Pas (Swing-helpdesk)
Dit is naar mijn weten **niet mogelijk**. Ik heb je vraag doorgestuurd aan de ontwikkelaars, wellicht dat er een truc voor is. Zo niet, dan zullen we hier een wens van maken.

**Comment by StefanJacques** [comment]
Sander Pas (Swing-helpdesk)
Op dit moment worden bij een **kaart presentatie** _standaard de korte namen van gebieden_ gebruikt, en bij andere presentatie vormen de volledige naam.
Ik heb als **wens** doorgegeven aan de ontwikkelaars om hier een instelling voor te maken zodat het _ook mogelijk is bij andere presentatievormen_.

**Comment by StefanJacques** [comment]
Sander Pas (Swing-helpdesk)
Ik heb een update ontvangen van de software ontwikkelaars.
Er wordt een **nieuwe opmaakinstelling aan de groep 'Labels' toegevoegd: 'Gebruik korte namen'**
Property naam in XML: **<UseShortNames>**
Deze aanpassing wordt in de volgende software release (over ongeveer 2 weken) doorgevoerd.
Deze opmaakinstelling kan je dus in een lay-out class van een rapport gebruiken.

**Comment by joostschouppe** [comment]
Dit schijnt opgelost te zijn
