### ISSUE TITLE
Standaard schalen van de header

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#23]
Op een laptopscherm, vooral met lagere resolutie, is de header van een Swing versie vaak veel te groot. Deze wordt niet geschaald, maar is uitgedrukt in het vaste aantal pixels van het logo van de Swing versie. Het zou beter zijn als dit dynamisch schaalt: bijvoorbeeld met de regel "geef weer als het kleinste van: 10% van de hoogte OF het aantal pixels van het logo". Bijvoorbeeld in Gent in Cijfers is de banner echt enorm op veel laptops. Een andere optie is om de header door de gebruiker te laten herschalen indien gewenst.

Prior omdat ik op zoek ga naar een kleiner logo voor Provincies in Cijfers als dit niet (snel) opgenomen kan worden.

**Comment by EdwardABF** [comment]
Het is mogelijk om bij kleinere schermen automatisch om te schakelen naar de 'Full screen modus'. In deze modus kan de header worden vervangen door een (kleiner) logo dat in de menubalk wordt getoond. Om dit te kunnen instellen ontvangen we graag een logo dat we hiervoor kunnen gebruiken. De overige instellingen kunnen jullie zelf in Studio doen (zie afbeelding).
![image](https://user-images.githubusercontent.com/31502648/30549807-127cc08a-9c96-11e7-8278-91b6d8941b3b.png)

**Comment by EdwardABF** [comment]
De header wordt vervangen door het (aangeleverde) logo bij de weergave op een tablet.
![image](https://user-images.githubusercontent.com/31502648/31078809-cce3b3c8-a783-11e7-8f6a-efbea9a69082.png)
