### ISSUE TITLE
Export naar excel knopje in rapporten is lelijk

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#25]
Het knopje om naar excel te kopiëren past niet bij de rest van de huisstijl.

![image](https://user-images.githubusercontent.com/10122639/30379397-a2c69a3e-9896-11e7-900f-c26b107c2d40.png)

In zwart-wit en meer gestileerd zou beter passen.

**Comment by EdwardABF** [comment]
Gemeld bij ontwikkelaars.

**Comment by EdwardABF** [comment]
Dit is aangepast in de nieuwe versie 5.3.0.

**Comment by joostschouppe** [comment]
Werkt live
