### ISSUE TITLE
Links vanuit naar PDF geëxporteerd rapport werken niet steeds

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#26]
Als je een rapport waarin je kan doorklikken naar de metadata vanuit een tabel exporteert naar PDF, dan werken de links niet meer. Een link ziet er bijvoorbeeld zo uit: https://stadincijfers.antwerpen.be/Databank/Jive//javascript:window.open('//stadincijfers.antwerpen.be/Databank/Jive//JiveObjectInfo.aspx?type=var&code=bevtot%27,%20%27Informatie%27,%20%27scrollbars=1,%20resizable=1,%20width=540,%20height=500%27);

Maar je PDF-reader kan hier wellicht geen blijf mee...

**Comment by EdwardABF** [comment]
Vanaf versie 5.3.0. zijn de iconen voor export naar tabel en Excel niet meer zichtbaar bij printen en de export naar pdf.
