### ISSUE TITLE
Laat in Studio in de header zien in welke versie je aan het werken bent

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#27]
In Studio staat enkel het logo van Swing. Het zou handig zijn als naast dat logo ook het logo van de versie zelf zou staan (het Provincies in Cijfers logo, het Limburg logo, het Antwerpen logo). Voor mensen die in meerdere versies werken, is het anders te gemakkelijk om zich te vergissen van versie.

**Comment by EdwardABF** [comment]
De header in Studio is momenteel niet instelbaar. Als wens ingediend om dit instelbaar te maken (net als in Jive). Aangemeld als issue SWI-58808.

**Comment by EdwardABF** [comment]
Naam van versie zichtbaar in header (vanaf versie 5.3):
![image](https://user-images.githubusercontent.com/31502648/37393713-230c11f0-2772-11e8-820b-384c89a004e7.png)
