### ISSUE TITLE
Buurt/wijk/.... onbekend wordt niet geaggregeerd op stadsniveau

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#36]
Buurt onbekend (code 9999) wordt door ons mee ingeladen.
We merkten op dat deze niet goed mee geaggregeerd wordt...

Ik heb wat uitzoekwerk gedaan en volgens mij ligt de 'fout' in het gegeven dat voor het gebiedsniveau  'gordel' geen gebied onbekend is gedefinieerd.  De 'children' van Antwerpen zijn namelijk, District, Onderwijszone en Gordel.  Enkel voor die laatste is er geen gebied onbekend aanwezig.

Zou dit kunnen gebeuren zodat de parent van Gordel (nl. stad Antwerpen) altijd het juiste aantal weergeeft? Dit mag met gebiedscode 'onb' en gebiedsnaam 'Onbekend'.

**Comment by EdwardABF** [comment]
Aan het gebiedsniveau ‘Gordel’ is het gebied ‘Onbekend’ toegevoegd en de aggregaties (wijk naar gordel en gordel naar Antwerpen) zijn aangepast.
