### ISSUE TITLE
mogelijkheid buurt onbekend zichtbaar maken in swing?

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#37]
We gebruiken in Stad in Cijfers 'buurt onbekend' als onbekend gebied.

Momenteel is het zo dat wij 'buurt onbekend' ingesteld hebben als "Toontype = Gebruiken voor aggregeren en niet tonen".  

We doen dit omdat het alternatief "Tonen" rare en onzinvolle effecten heeft. Bijvoorbeeld kan dit percentages van 500% opleveren, wanneer de teller meer moeite heeft met het lokaliseren van de informatie dan de noemers. Bovendien gebruikt Swing deze vreemde waarden dan ook voor het berekenen van de schaal van kaarten (waardoor je zeer vreemde klassenindelingen kunt krijgen).

Maar die oplossing is ook niet ideaal. Want het feit dat deze data niet getoond wordt maar wel gebruikt wordt om het stadstotaal weer te geven is verwarrend voor een gebruiker. Het gebeurt vaker dat iemand totalen van alle buurten, wijken, ... opvraagt en dit vergelijkt met het aantal voor de gehele stad - en dan vaststelt dat deze niet overeenkomen. 

Wij dachten daarom aan een compromis. Laat de waarden voor "gebied onbekend" wel steeds zien, maar laat ze niet zien als het om berekende cijfers gaat.
Dus aantallen (enkel in de zin van absolute aantallen) worden wel getoond voor "gebied onbekend". Maar als het onderwerp met een ander datatype dan ‘aantal’ wordt ingelezen (percentage, score, …) of als er met dit onderwerp een bewerking wordt gedaan in swing (percentage gemaakt, score, ...) de waarde op ‘niet van toepassing’ wordt gezet, zodat er geen waarde voor dit gebied kan getoond worden en deze ook niet mee in rekening wordt gebracht voor berekende onderwerpen. 

Kan dit geprogrammeerd worden?

**Comment by joostschouppe** [comment]
Lijkt mij een goed idee. Wat wel een praktisch bezwaar zou kunnen zijn:
- stel je hebt teller 500 werklozen en 50 bewoners in gebied onbekend
- percentage van dit gebied is natuurlijk onzin
- maar zowel teller als noemer moet je wel meenemen voor de berekening voor het totaal

Dus moet Swing dit percentage echt gaan censureren op het moment dat de data op een laag gebiedsniveau wordt berekend, maar de gegevens wel in de berekening meenemen indien het geaggregeerd wordt. Met andere woorden: het stadstotaal mag niet per ongeluk mee gecensureerd worden als er toevallig op een onderliggend niveau een waarde ontbreekt.
