### ISSUE TITLE
gestapelde bevolkingspiramide

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#40]
Is dit soort grafiek mogelijk in Swing? Indien niet, kan dit momgelijk gemaakt worden?

![image](https://user-images.githubusercontent.com/10122639/31603783-81eca4a4-b261-11e7-8f76-88cff50f18fc.png)

**Comment by EdwardABF** [comment]
Aangemeld als wens met ticketnummer 70630.

**Comment by EdwardABF** [comment]
Beschikbaar vanaf versie 5.4.0 (november/december 2018).
![image](https://user-images.githubusercontent.com/31502648/44580465-46d58280-a79a-11e8-9e11-8b2eaf5c687a.png)
