### ISSUE TITLE
laat 0 zien, ook al is 0 kleiner dan de drempelwaarde

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#41]
Is het mogelijk om in Swing ervoor te zorgen dat de afwezigheid van iets in een bepaalde categorie kan weergegeven worden? Met name bij kubussen zou het handig zijn als je kan aan en uitzetten of een nul-waarde getoond mag worden.
Bijvoorbeeld zou je zo het verschil kunnen maken tussen een "onbewoond gebied" en een "gebied met te weinig inwoners om te laten zien".

**Comment by EdwardABF** [comment]
Is ingebouwd en beschikbaar vanaf versie 5.3.0 als optie bij de instellingen (staat standaard uit):

![image](https://user-images.githubusercontent.com/31502648/36205002-81687d60-118d-11e8-8f0b-cf96c9968b0a.png)

**Comment by joostschouppe** [comment]
Super!
