### ISSUE TITLE
Gemeente in rapport vergelijken met een "zelf aangemaakte" gebiedsgroep ?

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/bugsinjive#42]
De titel spreekt waarschijnlijk voor zich ?

De **klant maakt een gebiedsgroep aan** van enkele gemeenten (x-aantal willekeurige gebieden = gebiedsgroep X).
Wij bieden een rapport aan waarin een gemeente standaard vergeleken wordt met bepaalde gebiedsniveaus.

Op welke manier kan er in een rapport dan ook de gebiedsgroep X verschijnen, waarmee we de gemeente kunnenvergelijken ?

**Comment by joostschouppe** [comment]
Of anders uitgedrukt: in de instellingen van het rapport, bepalen we nu zelf welke gebiedsniveaus als "geocompare" gekozen kunnen worden. Om deze vraag mogelijk te maken, zou je daar dus ook de mogelijkheid "gebiedsgroepen" moeten kunnen aanzetten. Het rapport zou dan nog zelf moeten opvragen welke gebiedsgroepen beschikbaar zijn.

Dit lijkt ons zelf nagenoeg onoplosbaar, maar dat is misschien niet juist.

Een concrete use-case: gemeente X wil zich vergelijken met "zijn omliggende gemeenten". Dat kunnen we mogelijk maken door het kiezen van meerdere gebieden op hetzelfde gebiedsniveau mogelijk te maken, en deze vergelijkingsgebieden op te tellen tot één vergelijkingsgebied. Dit lijkt ons wel mogelijk, en dan kan dit ook als link bewaard worden op deze manier.
