### ISSUE TITLE
Sorteren op basis van kubussen werkt niet

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#46]
Als je in Swing een kubusdimensie bevraagt en vervolgens probeert te sorteren op grootte, dan krijg je vreemde resultaten, zowel in Antwerpen als Provincies:

https://provincies.incijfers.be//jive?sel_guid=f10edc8d-d054-457f-8e00-fe5c3ad40780
https://stadincijfers.antwerpen.be/Databank/Jive/?sel_guid=95b82bea-f8fa-4a89-8625-94117fd837fc

**Comment by StephaniePeeters** [comment]
Dit is niet enkel in kubussen, ook bij gewone onderwerpen.
Is echt wel belangrijk dat dit gefixt wordt. 
We krijgen er binnen de stad reeds enkele meldingen over binnen.

**Comment by joostschouppe** [comment]
Inderdaad, gebeurt bij ons ook, zie [voorbeeld](https://provincies.incijfers.be//jive?sel_guid=af81c29f-2728-440c-9901-9e143e45b9cb).
Het lijkt precies wél opgelost in [de nieuwe versie](https://accept-provincies.incijfers.be//jive?workspace_guid=beb466ae-d2c4-4a7c-933e-de2160be6d00), ook [voor kubussen](https://accept-provincies.incijfers.be//jive?workspace_guid=548a1f00-3e5b-48c9-811b-9069d64fd029)

**Comment by EdwardABF** [comment]
Dit is inderdaad opgelost in de nieuwe release:

https://accept-antwerpen.buurtmonitor.be/Databank/Jive/?workspace_guid=52f7a285-1d5a-424e-95b0-fed6b3477b71

Ik vraag nog na of dit ook in de huidige versie wordt aangepast.

**Comment by EdwardABF** [comment]
Vanaf komend weekend opgelost in nieuwe versie.
