### ISSUE TITLE
Data>Importeren heeft ander resultaat dan Onderwerpen>Data Importeren

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#48]
Als je via Onderwerpen>Data Importeren data oplaadt, dan wordt je data op een andere manier verwerkt door Swing dan wanneer je het via Data>Importeren doet.

Op basis van deze excel:
(tabblad 2011-2017_(M) , tabblad 2011-2017_(V) )

* Via Onderwerpen>Data Importeren kan je NIET kiezen welke tabbladen je wil importeren. Alle tabbladen worden opgeladen.
* Je krijgt géén foutmelding als je de excel inleest via Data>Importeren, wél als je via  Onderwerpen>Data Importeren dit oplaadt. Foutmelding is dat er "getal als tekst" wordt ingelezen. 
* Het Onderwerp waarop deze fout van toepassing is, wordt naar aanleiding van deze fout helemaal leeg gemaakt - bij de mannen. Bij de vrouwen gaat het over dezelfde kolom, met dezelfde foutmelding. Hier wordt de data wel ingelezen. Verschil is dat hier de eerste rij een getal bevat. MAAR: er zijn nog een heel aantal kolommen met af en toe een lege waarde, en daar komen geen foutmeldingen naar boven.

Opmerking: de lege cellen vervangen door 0 lost het probleem op.

DIT WORDT OPGENOMEN MET HELPDESK

**Comment by StefanJacques** [comment]
de foutmelding
![afbeelding](https://user-images.githubusercontent.com/31841732/31991334-cbf52252-b977-11e7-9dfd-432713d46652.png)

**Comment by joostschouppe** [comment]
Zou opgelost zijn in nieuwe versie.
