### ISSUE TITLE
Vergelijkingsgebied niet meenemen in schaalbepaling

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#5]
Wanneer het vergelijkingsgebied meegenomen wordt in de schaalbepaling, lijkt het steeds of alles zeer laag is uiteraard (zie voorbeeld). 

Voorbeeld: https://stadincijfers.antwerpen.be/Databank/Jive/?workspace_guid=68d7bde3-8b9f-42db-9f29-fb3f5acb14ba

Vroeger in de quickstep was dit niet het geval wat logischer is.  Graag terug aanpassen naar deze instelling?

**Comment by joostschouppe** [comment]
Blijkbaar niet eenvoudig om dat zomaar te doen. Er is echter een omweg gemaakt. Via de opmaakinstelling van je kaart kan je "Legenda grenzen op basis van alle gebieden" aanzetten in deze situatie. Voorbeeld: https://provincies.incijfers.be//jive?workspace_guid=c9cdc231-2b1c-4011-a4fd-5434df6fed6e
Lijkt me wel OK, heeft helaas te veel nadelen om zomaar standaard aan te zetten.
