### ISSUE TITLE
Drempelwaarde van een onderwerp moet blijven doorwerken op afgeleide 

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#51]
Probleem:
- teller heeft een drempelwaarde omwille van privacy
- noemer heeft een drempelwaarde omwille van privacy
- berekend percentage heeft een drempelwaarde omwille van statistische zinvolheid

Bij het berekenen van een percentage hierop, moet je in de praktijk kiezen welke van de drie je wil respecteren

Dit is in bijna alle gevallen op te lossen door een vinkje te voorzien bij je berekend onderwerp met de keuze "censureer op klassieke manier / censureer als een gebruikersonderwerp", zo denken we. 

Met de klassieke manier bedoelen we: zoals het nu gebeurt, je kan slechts één drempelwaarde instellen. OFWEL respecteer je de statistische zinvolheid, OFWEL de privacy van de teller, OFWEL de privacy van de noemer.
Met censureren als een gebruikersonderwerp bedoelen we: als één van de elementen onder zijn eigen drempelwaarde valt, dan is het resultaat gecensureerd. Misschien is een betere naam "respecteer alle onderliggende drempels"

Voor teller en noemer zelf, heb je drempelwaarde 5 ingesteld. Bij je breuk heb je drempelwaarde 100 op basis van drempelonderwerp *noemer* ingesteld. In de huidige werking van Swing wordt je drempelwaarde van teller en noemer zelf dan genegeerd. Een vinkje "respecteer onderliggende drempels" kan dan zorgen dat je resultaat toch nog gecensureerd wordt volgens de privacy-drempelwaarden.

onderwerp | drempel | drempelonderwerp
-- | -- | --
teller | 5 | null
noemer | 5 | null
breuk | 100 | noemer

Hieronder enkele scenario's:
In scenario 1 mag het resultaat niet getoond worden omdat er aan geen van de drie voorwaarden wordt voldaan.
In scenario 2 mag het resultaat niet getoond worden omdat de teller te klein is en omdat de noemer niet statistisch relevant is.
In scenario 3 mag het resultaat niet getoond worden omdat de noemer niet statistisch relevant is.
In scenario 4 mag het resultaat getoond worden omdat alle aantallen groot genoeg zijn.
In scenario 5 mag het resultaat niet getoond worden omdat de teller te klein is.

  | teller | noemer | breuk
-- | -- | -- | --
scenario 1 | 4 | 4 | *
scenario 2 | 4 | 95 | *
scenario 3 | 40 | 95 | *
scenario 4 | 40 | 105 | 38%
scenario 5 | 4 | 105 | *

In sommige omstandigheden wil je dit toch negeren. Bijvoorbeeld scenario 5 kan je besluiten dat de drempel op teller toch niet zo belangrijk is, als de bron niet zo heel streng is. Daarom is het belangrijk om het vinkje ook uit te kunnen zetten.

Er is nu nog steeds een probleem als je teller zelf zelf een formule is. Stel dat je twee leeftijdsgroepen optelt waarvan er één gecensureerd is. Het eindresultaat zal dan gecensureerd worden, zelfs als de som van die twee elementen boven de drempel uitkwam.

Misschien is dit toch nog oplosbaar. Je zou een onderwerp *teller* kunnen aanmaken die de som  teller_deelA+teller_deelB maakt. Dit onderwerp zeg je dan om de onderliggende drempels NIET te respecteren. Vervolgens kan je dit berekend onderwerp gebruiken zoals hierboven en in die formule WEL de onderliggende drempels respecteren.

**Comment by EdwardABF** [comment]
Ik heb jullie voorstel ingediend als wens onder ticketnummer 60000.

**Comment by joostschouppe** [comment]
Dit werkt in de nieuwe versie
