### ISSUE TITLE
BUG - kopiëren van thema in themaboom (sub-thema-namen worden vervangen door 'nieuw')

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/bugsinjive#52]
limburg.incijfers.be

ik kopieer het volledige thema VEILIGHEID

![afbeelding](https://user-images.githubusercontent.com/31841732/32493951-08a12276-c3c0-11e7-9100-557def948124.png)

naar een ander onderdeel in de themaboom
en alle subthema's krijgen de naam NIEUW

![afbeelding](https://user-images.githubusercontent.com/31841732/32494049-6e58283a-c3c0-11e7-9f4a-9d1fe9474d82.png)

**Comment by EdwardABF** [comment]
Dit lijkt te zijn opgelost in de nieuwe versie (5.2.0). Dit kunt u testen in de testversie die toegestuurd heeft gekregen.

**Comment by joostschouppe** [comment]
Dit is niet opgelost. Onderliggend probleem is [dit issue](https://github.com/provinciesincijfers/bugsinjive/issues/58). Maar dit wordt wellicht niet opgelost, aangezien bijna niemand aliassen gebruikt.
