### ISSUE TITLE
Sorteringsmogelijkheid bij onderwerptoekenning aan toegangsroepen

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#53]
Om te onderwerpen te selecteren kan je in de rechterkolom sorteren op alle mogelijke onderwerpkenmerken (zoals vb. bron).  In de linkerkolom als je onderwerpen wil verwijderen, gaat dit niet. Dit zorgt ervoor dat dit werk zeer arbeidsintensief is. 
Zou het mogelijk zijn dat de onderwerpen in de linkerkolom ook sorteerbaar zijn op hun kenmerken?

**Comment by joostschouppe** [comment]
Dit is een bug volgens mij, want je kan wel degelijk op Bron klikken om het te sorteren. Alleen klopt de sortering niet.

Wat misschien nu helpt: de meeste groepen zijn eenvoudig, dan kan je al beter gewoon alles wissen en gans opnieuw beginnen.

**Comment by EdwardABF** [comment]
Het sorteren gaat inderdaad niet goed. Dat zal ik doorgeven aan de ontwikkelaars.

Er is wel een workaround. Je kunt gebruik maken van de im- en exportfunctie bij de toegangsgroepitems (onder de tabel met 'zichtbare items'). Door ze eerst allemaal te exporteren, vervolgens alle regels te verwijderen en tot slot de (in Excel) aangepaste itemlijst weer te importeren.

![image](https://user-images.githubusercontent.com/31502648/32605326-58ce897c-c551-11e7-8f45-8402ecff9ec5.png)

**Comment by EdwardABF** [comment]
Het probleem met het sorteren van onderwerpen in toegangsgroepen is in versie 5.2.0 (uitrol vindt plaats binnen nu en twee weken) opgelost.
