### ISSUE TITLE
Bij export afbeeldingen, filmpjes, data, ook Swing-versie vermelden

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#56]
Wanneer je data exporteert uit Swing, dan krijg je altijd mooi de bron in beeld. Zou het ook niet goed zijn om daar aan toe te voegen: "Data beschikbaar gesteld via [url van de swing-versie]".

**Comment by EdwardABF** [comment]
Is het een idee om alle bronnamen te laten beginnen met 'provincie.incijfers.be'. dan krijg je als bronnaam bijvoorbeeld 'provincie.incijfers.be │Rijksdienst voor Pensioenen'.

**Comment by joostschouppe** [comment]
Ja, dit lijkt me een afdoende oplossing. Met mijn voorstel zou je dit wel in één keer bij al jullie klanten kunnen oplossen.
