### ISSUE TITLE
Om op te volgen: beheer thema Naam/Alias (ticket 59961)

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#58]
Doorgegeven aan ontwikkelaars door @sanderABF. 

Als je een Nieuw thema aanmaakt, en vervolgens de naam invult via de themaboom zelf (door bijvoorbeeld te dubbelklikken, F2 te toetsen of Wijzig Alias te klikken), dan ziet het eindresultaat er goed uit, terwijl op het niveau van de Themanaam er niets gewijzigd is.
Dit vind ik een minder intuïtieve oplossing. De standaardoperatie om een naam toe te voegen zou moeten zijn de naam toevoegen, niet een alias ingeven (klinkt logisch als je t zo zegt, niet?). Het lijkt mij ook handig als het vakje dat verschijnt als je Wijzig hebt aangeklikt, zowel de Naam als de Alias verschijnt.
Ik heb zelf al bijna 40 themas aangemaakt waar dit zich voordoet. En check even ticket 59721. Daar had Stefan een gek probleem als hij een stuk van zijn themaboom kopieerde. Ook dat is veroorzaakt door het feit dat daar systematisch per ongeluk alleen aliassen en geen themanaam zijn ingevoerd. Dus het onderliggende probleem is toen niet gedetecteerd en niet opgelost (maar gewoon niet gereproduceerd geraakt).
Een oplossing zou kunnen zijn om bij aanmaak van een nieuw thema de naam leeg te laten. De eerste interactie met naamgeving (ongeacht via welk knopje je het doet) verandert dan steeds de naam zelf. Pas als je daarna expliciet de alias wijzigt, wijzig je alleen de alias.

**Comment by joostschouppe** [comment]
Wordt niet opgelost omdat niemand deze functie zou gebruiken. @StefanJacques als je niet akkoord bent, best opnieuw inseinen. Voor zover ik weet, willen jullie de functie "aliassen in themaboom" ook uitzetten om dit probleem niet meer te hebben.

**Comment by EdwardABF** [comment]
De volgende aanpassingen met betrekking tot het gebruik van aliassen zijn gedaan:
- alias verschijnt cursief in themaboom (in Studio)
- de originele naam is opgenomen in een tooltip (in Studio)
- het opgeven van aliassen bij thema's is uitgeschakeld

Overigens zie ik dat het gebruik van de aliassen in jullie versie volledig zijn uitgeschakeld (bij de 'Instellingen'):
![image](https://user-images.githubusercontent.com/31502648/43777559-77a5bae6-9a53-11e8-84bf-c1337cb271f6.png)

**Comment by EdwardABF** [comment]
Excuus dan voor de miscommunicatie. Blijkbaar is naderhand toch besloten om enkele aanpassingen te doen om het gebruik van aliassen te verbeteren.
