### ISSUE TITLE
Export presentatie naar afbeelding

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#6]
Indien je een presentatie maakt en die exporteert als afbeelding, dan krijg je wel een titel, de schaal, de bron en de speciale waarde mee maar geen eenheid.

![aantal inwoners blootgesteld aan stikstofdioxide 28no2 29 boven eu norm 28_ 3d 40 g_m 29 2015 - postzones](https://user-images.githubusercontent.com/29600367/29569208-124fec8e-8753-11e7-89a0-a2a7766fc3a0.png)

**Comment by EdwardABF** [comment]
De eenheid wordt (bij afdrukken en exporteren) standaard in de legenda getoond. In jullie versie is deze optie uitgezet in de algemene opmaakinstellingen voor afdrukken (en exporteren). Om dit weer in te schakelen, kies in het menu 'Weergave' voor 'Opmaakinstellingen'. Er opent een nieuw scherm met de opmaakinstellingen. Selecteer nu in de drop-down linksboven in het scherm bij 'Sjabloon' voor 'Afdrukken'. Vink vervolgens bij 'Legenda' de optie 'Toon eenheid in legenda' aan (zie onderstaande afbeelding).

![image](https://user-images.githubusercontent.com/31502648/29921647-aec5fac6-8e52-11e7-8d0c-bfc61c9d240c.png)

**Comment by joostschouppe** [comment]
OK, bedankt!
