### ISSUE TITLE
Op te volgen: maximale grote van een kubus-inlaadbestand (ticket 59600)

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#60]
Antwoord de goed van @sanderABF sinds 20/11/2017.
Ook CSV heeft maximaal aantal rijen of bestandsgrootte die Studio kan slikken. Welke?

**Comment by joostschouppe** [comment]
Opmerking: dit stond nog open in [issue 3](https://github.com/provinciesincijfers/bugsinjive/issues/3), die ik net heb afgesloten.

**Comment by sanderABF** [comment]
Er is geen maximum aantal rijen of bestandsgrootte dat Studio kan verwerken; wel een maximum aantal kubuscombinaties (max 500.000). 
Jullie database is nog van het type Acces, dit kunnen we omzetten naar SQL Server. Dat zal onder andere het inlezen van kubussen versnellen.  Geef maar aan of jullie dit willen doen, dan spreken we een tijdstip af om dit uit te voeren. Dit neemt 2 uur in beslag, Studio zal in die tijd niet bereikbaar zijn. De Viewer blijft wel online.

**Comment by joostschouppe** [comment]
@sanderABF ik heb nochtans problemen gehad met heel grote inleesbestanden (een tiental miljoen rijen). Moet ik je een groot bestand bezorgen om mee te spelen?

**Comment by sanderABF** [comment]
Prima, stuur maar op.
