### ISSUE TITLE
Filteren op gebiedsniveau door gebruiker

### ISSUE THREAD

**Issue by BartDaemen** [provinciesincijfers/bugsinjive#64]
Gebruikers van een databank die werken met een onderwerp op wijk- of statsector-niveau zijn vaak gefrustreerd dat deze tabel zich aanpast van zodra ze een extra onderwerp selecteren dat enkel op stadsniveau beschikbaar is. Tabel past zich dan (correct) aan tot het kleinste gemeenschappelijk beschikbare niveau (niveau stad). 

Vanuit diensten komt dan vaak de vraag naar een overzicht van alle gegevens beschikbaar op wijkniveau. Dit kan een beheerder door alle onderwerpen die beschikbaar zijn op wijkniveau samen te brengen in map in themaboom, maar dit is beetje omslachtige oplossing. 

Daarom suggestie om na te denken om dit te integreren in gebruikers-interface: 
- bijvoorbeeld mogelijkheid om te filteren op beschikbaarheid gebiedsniveau bovenaan in themaboom (cfr zoekveld) zodat enkel onderwerpen beschikbaar op bepaald niveau getoond worden
- of als onderwerp met bepaald gebiedsniveau éénmaal geselecteerd is, andere onderwerpen die ook op dit niveau beschikbaar zijn, visueel te markeren
- of misschien nog andere betere oplossing?

**Comment by joostschouppe** [comment]
Via Data>Data instellingen>Combineer gebiedsniveaus kan je er nu voor zorgen dat je alle beschikbare gebiedsniveaus van alle data krijgt. Als je dus een onderwerp op statsec met een op gemeente combineert, en je kiest statsec, dan krijg je een tabel waarbij het gemeente-onderwerp gewoon leeg blijft.
