### ISSUE TITLE
Fout met geolevels bij importeren rapport basisonderwijs

### ISSUE THREAD

**Issue by KrisDegryse** [provinciesincijfers/bugsinjive#65]
Als 'Stad Roeselare' hebben wij het rapport 'OBMI_basisonderwijs.sw5r' ingeladen. In de code van het rapport werd een input_geo gedefinieerd met 4 geolevels: [Geo.sector, Geo.wijk, Geo.gemeente, Geo.stadsregio].
Wij hebben het geolevel 'stadsregio' niet ter beschikking. Mijn collega gaf aan om sector, wijk, deelgemeente (i.p.v. gemeente) en gemeente (i.p.v. stadregio) te gebruiken. Bij het testen van de code van het rapport krijg ik volgende foutmelding:
   **Unexpected error: The specified ID 'wijk' is not unique, use a qualifier. in element if Equal then # ## # end    ifelse # ## #end ifenif(0)**
Enig idee wat hier misloopt?

**Comment by KrisDegryse** [comment]
![geolevels-obmi_basisonderwijspng](https://user-images.githubusercontent.com/34096369/51517670-c8017600-1e1b-11e9-8ff8-77f68213fb23.png)
Screen shot van foutmelding!

**Comment by joostschouppe** [comment]
Ik ga ervan uit dat dit al opgelost is via een andere weg?
Klinkt alsof er iets speciaals aan de hand is met jullie gebiedsniveau "wijk"

**Comment by KrisDegryse** [comment]
Klopt, dit werd opgelost door het nieuwe rapport dat door Annelies van de Stad Gent werd aangereikt.
