### ISSUE TITLE
Kaartlagen kernwinkelgebied en winkelgebieden niet zichtbaar

### ISSUE THREAD

**Issue by dimitrivanbaelen** [provinciesincijfers/bugsinjive#67]
De kaartlagen kernwinkelgebied en winkelgebieden worden niet meer zichtbaar als die aangeduid worden in de visualisatie.  Is er misschien iets aan de URL van de WMS gewijzigd?  Want als ik in PiC het rapport Detailhandel bekijk, staat daar wel een kaartje in.

**Comment by joostschouppe** [comment]
Dimitri, waar gebruik je dit? We hebben effectief deze WMS server uitgezet omdat we nu met een volwaardig gebiedsniveau binnen Swing werken. Sint-Niklaas heeft dat ondertussen ook gedaan. Dat kunnen jullie eventueel ook doen?

**Comment by dimitrivanbaelen** [comment]
Hallo Joost,

We hebben momenteel zowel het kernwinkelgebied als de opsplitsing van de winkelgebieden als een beschikbare kaartlaag, naast de contouren en OpenStreetMap.  Ze als een gebiedsniveau definiëren is voor mij ook een valabele optie.  Hoe kan ik dat het best doen?

Met vriendelijke groeten,

Dimitri Van Baelen | Beleids- en Managementinformatie Manager
Groep Mechelen | Strategie en ontwikkeling
Bezoekadres: Huis van de Mechelaar, Reuzenstraat 1, 2800 Mechelen
Postadres: Grote Markt 21, 2800 Mechelen

T 015 29 78 22 | M 0494 45 21 99
F 015 29 75 10 | E dimitri.vanbaelen@mechelen.be<mailto:dimitri.vanbaelen@mechelen.be>
W www.mechelen.be<http://www.mechelen.be/>
Volg ons op Facebook<http://www.facebook.com/StadMechelen> of Twitter<http://twitter.com/StadMechelen>

**Comment by joostschouppe** [comment]
Ondertussen wellicht opgelost tussen Mechelen en ABF

**Comment by dimitrivanbaelen** [comment]
Hallo Joost,

Klopt inderdaad, ondertussen heb ik de twee bijkomende gebiedsniveau operationeel gekregen in de Studio en Jive.

Bedankt!

Met vriendelijke groeten,

Dimitri Van Baelen | Beleids- en Managementinformatie Manager
Groep Mechelen | Strategie en ontwikkeling
Bezoekadres: Huis van de Mechelaar, Reuzenstraat 1, 2800 Mechelen
Postadres: Grote Markt 21, 2800 Mechelen

T 015 29 78 22 | M 0494 45 21 99
F 015 29 75 10 | E dimitri.vanbaelen@mechelen.be<mailto:dimitri.vanbaelen@mechelen.be>
W www.mechelen.be<http://www.mechelen.be/>
Volg ons op Facebook<http://www.facebook.com/StadMechelen> of Twitter<http://twitter.com/StadMechelen>
