### ISSUE TITLE
Foutmelding in rapporten sinds laatste update Swing Studio

### ISSUE THREAD

**Issue by liesbetvandriessche** [provinciesincijfers/bugsinjive#76]
Sinds de nieuwe update van Swing Studio (vorige week?) krijg ik bij een reeks rapporten foutmeldingen. O.a. bij de stadsdeelrapporten van de Stadsmonitor. bijvoorbeeld: Stadsdeelrapport Armoede: foutmelding: [* Warning 'geolevel' is a reserved word and cannot be used as a variable name. at line 41, column 0 *] // rapport bevolking: foutmelding [* Warning: Do not place an input specification inside 'if then' statement. Conditional input not supported at line 47, column 20 *] // Het gaat om rapporten waarbij je een eigen gebied en keuzegebieden kunt instellen.

**Comment by joostschouppe** [comment]
Doet zich bij ons ook voor. Die "geolevel" error kan je voorlopig negeren; is LIVE niet zichtbaar. Die "if then" is bij ons ook lastig. Ook deze geeft live GEEN problemen; maar je kan wel niet meer in je rapport werken dankzij deze melding.

**Comment by liesbetvandriessche** [comment]
Als ik het goed begrijp, kan ik dus wel Swing Studio publiceren zonder dat die errors zouden zorgen voor een fout in de LIVE rapporten? En is het dus alleen lastig werken als je een rapport wilt aanpassen?

**Comment by joostschouppe** [comment]
Dat lijkt me wel. Maar we kunnen het natuurlijk niet negeren, want we kunnen nu niet meer in die rapporten bewerken!
Wij hebben hier ook al een melding over gedaan bij ABF.

**Comment by EdwardABF** [comment]
Het idee achter de diverse foutmeldingen is om de beheerder de rapportcode (SRL) zo goed mogelijk te laten opzetten. De vermelde fouten kunnen namelijk leiden tot het verkeerd weergeven van het rapport. Bij de meeste foutmeldingen wordt het rapport gewoon getoond, maar bij het specifieke geval van de inputs in een if-then-statement wordt de hele inhoud geblokkeerd. Dat gaat wat te ver en dat zal dus worden aangepast, zodat de inhoud weer getoond wordt. Ik verwacht dat dit deze week nog zal zijn aangepast.

Neemt niet weg dat dit dus beter kan worden opgezet door het variabele gedeelte buiten de input te bepalen en het dan op te vragen in de input. Als daar hulp bij nodig is dan helpen wij uiteraard graag.

**Comment by joostschouppe** [comment]
Kan dat voor dit soort code?

```

input_geo=input
{
    Type: Geo;
    Caption: "Kies gebieden";
    Instruction: "Kies een gebied";
    Level: [Geo.statsec, Geo.ggw7, Geo.deelgemeente, Geo.gemeente];
    Min: 1;
    Max: 1;
}

if Equal(level(input_geo), "gemeente") then

Subset_conditonal = ListJoin(Parents(input_geo),Siblings(input_geo))

else

Subset_conditonal = parents(input_geo)

end if

input_compare = input
{
    Type: GeoItem;
    Caption: "Keuze vergelijkingsgebied";
    Instruction: "Kies 3 vergelijkingsgebieden";
    Subset: Subset_conditonal;
    Default: [arrondiss._99999, provincie._99999, gewest._99999];
    Min: 3;
    Max: 3;
} 
```

**Comment by EdwardABF** [comment]
Ja, dit is de 'oplossing' die ik vanochtend in een van de rapporten heb toegepast en de 'juiste' manier om de input dynamisch/conditioneel te maken.

**Comment by EdwardABF** [comment]
De geel gearceerde code is nieuw en vervangt de 'dubbele' inputs met een input waarin een conditionele variabele is opgenomen:
![image](https://user-images.githubusercontent.com/31502648/74728458-16618e00-5243-11ea-99c0-b8a89f90ffd0.png)

**Comment by liesbetvandriessche** [comment]
Ik heb de code als volgt aangepast. [code.txt](https://github.com/provinciesincijfers/bugsinjive/files/4225418/code.txt)
De '#' geven nog een probleem. Zet ik ze niet dan worden de presentaties niet gevonden, zet ik ze wel dan verschijnt de If Equal tekst boven het rapport.
![Knipsel](https://user-images.githubusercontent.com/45195886/74840943-21dab500-5328-11ea-9759-72a574a108f8.PNG)

**Comment by joostschouppe** [comment]
Zoals nu in je txt staat, ontbreek je een "afsluitende" # voor "#if Equal" en een "openende" voor "input_compare". Ofwel moet je alle # van heel het stuk in het midden verwijderen

**Comment by liesbetvandriessche** [comment]
Ik blijft foutmeldingen krijgen?
[code wijkrapport.txt](https://github.com/provinciesincijfers/bugsinjive/files/4235664/code.wijkrapport.txt)

![Knipsel](https://user-images.githubusercontent.com/45195886/75028534-b2d49c00-54a0-11ea-9185-ffefd8d0d994.PNG)

**Comment by EdwardABF** [comment]
Hoi Liesbeth, Ik wil er graag naar kijken. Ben je nu bezig in het rapport? Gr, Edward

**Comment by liesbetvandriessche** [comment]
Dag Edward, neen ik ben er niet meer in bezig. 
bedankt om ernaar te kijken.

**Comment by EdwardABF** [comment]
Hoi Liesbeth, het ging (nog) fout bij het opvragen van het gebiedsniveau uit de input_geolevel. Dat deed je met 'level(input_geolevel', maar dat is dubbel op, input_geolevel is al op het niveau 'level'.  Nu dat is aangepast werkt het rapport zonder foutmelding.

Als je een gemeente kiest vraag je in subset van de input_compare om de 'siblings' van de gemeente, maar die zijn er niet in het gebiedsniveau 'gemeente'. Het zou wel interessant zijn om een andere centrumgemeente te kunnen kiezen. Als dat wenselijk is, kan ik kijken of dat mogelijk is.

![image](https://user-images.githubusercontent.com/31502648/75031448-8ae83700-54a6-11ea-969e-4da54b637823.png)

**Comment by liesbetvandriessche** [comment]
Dag Edward,
Bedankt. Ik probeer het rapport deze namiddag online te plaatsen.
Het rapport is op maat van de wijkteams van stad Kortrijk. Zij wensen vooral hun eigen wijk te zien. Een vergelijking met andere centrumsteden hoeft voor hen niet. Ik dacht ook dat we in het OBMI overleg hadden afgesproken om in stad.incijfers enkel cijfers te tonen van de eigen stad en niet van andere centrumsteden. @joostschouppe , Klopt dit?

**Comment by liesbetvandriessche** [comment]
Edward,
De gebiedskeuze van het rapport is in orde, dank je wel.
Echter zijn de presentaties waar 'Geo.gemeente' als gebied in de code staat (omdat deze gegevens enkel op stadsniveau beschikbaar zijn) niet meer zichtbaar.

pres_8 = Presentation {
                	Selection {
                		Ind.budgetmeters;
                		MostRecentPeriod: 1;
                		Geo.gemeente;
        		        SplitUp: input_geolevel;
        		        
        		  	};
                	View: Map;
                	ViewDimensions: [dim_geo, dim_variable];
                	Title:  "Actieve budgetmeters gas en elektriciteit 2018";
                	LayoutClass: "pres_1";
                    }

**Comment by EdwardABF** [comment]
Ik heb hiervoor waarschijnlijk wel een oplossing. Ik kan die alleen niet testen omdat er iets mis lijkt te gaan met het aanmaken van presentaties in het rapport. Dat heb ik doorgegeven aan de ontwikkelaars.

**Comment by EdwardABF** [comment]
Hoi Liesbeth,

Het probleem met de weergave van presentaties in rapporten is opgelost. Ik heb nu ook een voorbeeld gemaakt waarin de keuze voor 'gemeente' toch alle presentaties (voor zover ik kon zien) getoond worden. Het probleem zit in de 'SplitUp'. De gemeente kan je namelijk niet uitsplitsen naar naar het gebiedsniveau 'gemeente'. Door de 'SplitUp' conditioneel te maken, kan je hiervoor een uitzondering maken. Als een gebruiker nu 'gemeente' kiest dan staat het gebiedsniveau bij de 'SplitUp' vast op 'wijk' en in de overige gevallen op het gekozen gebiedsniveau.

[https://kortrijk.incijfers.be/admin/jive/Report/Edit/test_abf](url)

![image](https://user-images.githubusercontent.com/31502648/75150425-a0f33300-5704-11ea-80a7-8ab34e8586c2.png)

![image](https://user-images.githubusercontent.com/31502648/75150436-a6507d80-5704-11ea-938c-d8701feda7e5.png)

Groet, Edward

**Comment by liesbetvandriessche** [comment]
Edward,

bedankt!

groeten,
Liesbet
