### ISSUE TITLE
Instellen van kleuren per type grafiek

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#79]
In Swing Viewer worden standaard deze kleuren gebruikt (toch in kaarten):
Sequential: platte aantallen, percentages
Diverging: z-scores (gevraagd via transformaties), gemiddelden

Wij zouden graag z-scores anders inkleuren van gemiddelden. Immers heeft bij de ene de kleuring een echte betekenis (grijs = gemiddeld) en bij het andere niet (grijs is de groep die door swing in de middelste klasse wordt geduwd, maar dat kan veel hoger of lager dan gemiddeld zijn afhankelijk van de verdeling)

Melding 87358: dit is niet aanpasbaar. Lijkt me een grotere wens; zijn er nog mensen die dit graag zouden hebben?

Ter illustratie: een eindgebruiker zal onterecht de eerste kaart interpreteren zoals die dat zou doen voor de tweede. terwijl het toch duidelijk over iets anders gaat!
![afbeelding](https://user-images.githubusercontent.com/10122639/76603687-b42c3e00-650d-11ea-8a74-25f1d48e90b4.png)

Online: https://provincies.incijfers.be//jive?workspace_guid=0ada110f-6ce2-4edd-bea7-5a23ca6d993c

**Comment by liesbetvandriessche** [comment]
Het lijkt mij inderdaad interessant om andere kleuren te kunnen gebruiken bij z-scores om de leesbaarheid van de kaarten voor de eindgebruiker te verbeteren.

**Comment by joostschouppe** [comment]
Opgelost in nieuwe versie
