### ISSUE TITLE
Kaartbevraging bij animatie kaart loopt zeer traag

### ISSUE THREAD

**Issue by StephaniePeeters** [provinciesincijfers/bugsinjive#8]
- WENS: als je een kaartje animeert (op play klikken om de evolutie als filmpje te zien), dan moet Jive steeds een nieuwe kaartbevraging doen. Daardoor verdwijnt de achtergrondkaart telkens even uit beeld. Kan Jive die kaart even cachen om de wachttijd en de visuele afleiding te vermijden? Of indien niet, kan bij het activeren van een geanimeerde kaart de achtergrondkaart tijdelijk uitgezet worden?
    - Ik zie de kaart (basiskaart Stad Antwerpen) niet (meer) verdwijnen.
      - 2016/09/01: in dit voorbeeld is het bij mij redelijk extreem: https://stadincijfers.antwerpen.be/Jive?sel_guid=cc10212c-bbf9-43a9-a8d2-074dc6a3a72c

  **Gemeld bij ontwikkelaars: http://bugnet/Issues/IssueDetail.aspx?id=45 791.

  **De kaarten worden nu van tevoren geladen waarna het afspelen van perioden soepeler verloopt. Het starten van de animatie wordt hierdoor wel iets vertraagd. Ik hoor het graag als jullie de vertraging te lang vinden. Misschien kan er nog melding komen van de vertraging.
    - Vertraging zoals ze nu is lijkt mij aanvaardbaar. Als er een extra melding komt, zou ik eerder opteren voor iets als: "Voor een vlottere animatie, is het best Kaartlagen uit te schakelen".

**Comment by StephaniePeeters** [comment]
Vertraging is aanvaardbaar TENZIJ je een oude trage pc hebt blijkbaar.
Dan blijf je een beetje gejost...

**Comment by joostschouppe** [comment]
Goed genoeg :)
