### ISSUE TITLE
Excel lijst van de 14 landengroepen

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/bugsinjive#80]
Kan ik een gedetailleerd overzicht krijgen van alle landen met daarbij de landengroep waartoe ze behoren (in Excel)?

**Comment by joostschouppe** [comment]
Als ik het goed heb, heb je dit rechtstreeks met Rudy opgelost?
(heropen gerust als ik het fout heb)

**Comment by anneliesvs** [comment]
Idd. thx

Groeten

Annelies
0485 57 43 78

Van: Joost <notifications@github.com>
Verzonden: dinsdag 31 maart 2020 14:26
Aan: provinciesincijfers/bugsinjive <bugsinjive@noreply.github.com>
CC: Van Steenberge Annelies <Annelies.VanSteenberge@stad.gent>; Author <author@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/bugsinjive] Excel lijst van de 14 landengroepen (#80)


Als ik het goed heb, heb je dit rechtstreeks met Rudy opgelost?
(heropen gerust als ik het fout heb)
