### ISSUE TITLE
Infodocument linken aan detailview in Mosaic bij een 'combined indicator'

### ISSUE THREAD

**Issue by WouterDeSpiegelaere** [provinciesincijfers/bugsinjive#95]
Aan iedere indicator kan je simpel een infodocument (vb. pdf) hangen. Deze infodocument is dan selecteerbaar in de detailview van  de indicator in de dashboard. Echter hoe kan je dezelfde functie gebruiken als je meerdere indicatoren gecombineerd hebt in één indicator/tegel? Ik krijg het infodocument niet zichtbaar ook al is het gekoppeld aan elke indicator afzonderlijk. Iemand een idee?

**Comment by joostschouppe** [comment]
Dat is op dit moment niet mogelijk. Ik spreek binnenkort af met ABF rond de weergave van metadata, en zal meenemen dat jij dit ook vroeg. Maar schiet gerust ook een wens in rechtsreeks bij ABF.

**Comment by joostschouppe** [comment]
De manier waarop je in Dashboard met Metadata om kunt gaan verandert volledig. Hierdoor wordt deze aanpassing minder belangrijk
