### ISSUE TITLE
'Mediaaninkomen per aangifte' by default uitgesplitst naar statistische sectoren

### ISSUE THREAD

**Issue by liesbetvandriessche** [provinciesincijfers/bugsinjive#97]
De indicator 'Mediaaninkomen per aangifte' met code dna_v1203_mediaan staat by default uitgesplitst naar statistische sectoren voor de gebiedsniveaus 'deelgemeenten' en 'wijken'. Je kan deze uitsplitsing manueel niet uitschakelen. Als gevolg hiervan krijg je altijd tabellen en grafieken met de statistische sectoren terwijl je soms enkel de data per wijk of gemeente wenst.
![Github_issue_uitsplitsing_statsec2](https://user-images.githubusercontent.com/45195886/120613274-5d828b00-c456-11eb-89ea-a2b3b907d8f9.JPG)
![Github_issue_uitsplitsing_statsec1](https://user-images.githubusercontent.com/45195886/120613281-5e1b2180-c456-11eb-8021-677ee1cf004b.JPG)

**Comment by joostschouppe** [comment]
Dat is normaal, aangezien deze indicator niet aggregeerbaar is.
We zijn wel al enkele maanden data van statbel aan het goed zetten om dit nu wel op wijkniveau aan te kunnen bieden. De wijken zijn op elkaar afgestemd, dus in principe zou de connector die dan doorzetten. Als jullie deelgemeenten afgestemd zijn op de onze, dan zouden ook die door kunnen stromen; mits een extra ingreep van Richard.
