### ISSUE TITLE
Legende bij gebruik z-scores + consistentie van info bij legenda

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/bugsinjive#98]
* Idealiter toont de z-kaart niet enkel "hoger" maar ook de effectieve klassengrenzen. ABF is niet enthousiast over dit idee (ticket 87181, update 2021/04), dus dat komt er wellicht NIET aan.
* Toon vergelijkingsgebied steeds in de legende van de kaart (zie issue 107811)

**Comment by joostschouppe** [comment]
Nog eens op aangedrongen via 87181 (15/3/2022) met vermelding issue 107811

**Comment by joostschouppe** [comment]
Ticket 87181 zal niet opgenomen worden.

**Comment by Emilien-Dupont** [comment]
Ticket 107811 zal ook niet opgenomen worden
